---
--- Generated by Luanalysis
--- Created by taojiaqi.
--- DateTime: 2023/5/27 10:41
--- 参数列表
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0)
then
    return 1
end

--判断用户是否下单SISMEMBER key
if (tonumber(redis.call('sismember', orderKey, userId)) == 1)
then
    return 2
end

redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'orderId', orderId)
return 0
